/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/《局外人》，《窄门》': RouteRecordInfo<'/posts/《局外人》，《窄门》', '/posts/《局外人》，《窄门》', Record<never, never>, Record<never, never>>,
    '/posts/此去经年，应是良辰好景虚设': RouteRecordInfo<'/posts/此去经年，应是良辰好景虚设', '/posts/此去经年，应是良辰好景虚设', Record<never, never>, Record<never, never>>,
    '/posts/计算机考研篇': RouteRecordInfo<'/posts/计算机考研篇', '/posts/计算机考研篇', Record<never, never>, Record<never, never>>,
    '/posts/起点': RouteRecordInfo<'/posts/起点', '/posts/起点', Record<never, never>, Record<never, never>>,
    '/posts/如何使用github': RouteRecordInfo<'/posts/如何使用github', '/posts/如何使用github', Record<never, never>, Record<never, never>>,
    '/posts/Bye,HAU': RouteRecordInfo<'/posts/Bye,HAU', '/posts/Bye,HAU', Record<never, never>, Record<never, never>>,
    '/posts/others/我亦飘零久': RouteRecordInfo<'/posts/others/我亦飘零久', '/posts/others/我亦飘零久', Record<never, never>, Record<never, never>>,
    '/posts/TheWinter/TheWinter': RouteRecordInfo<'/posts/TheWinter/TheWinter', '/posts/TheWinter/TheWinter', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
